version: '3.7'

services:
  nginx:
    restart: always
    build: docker/nginx
    ports:
      - "80:80"
    expose:
      - "80"
    links:
      - web:web
    depends_on:
      - web
    volumes:
      - .:/app

  web:
    restart: always
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - .:/app
    env_file:
      - docker/web/env.env
    environment:
      DEBUG: 'true'
    working_dir: /app
    command: >
      sh -c "python manage.py collectstatic --settings=hopla.settings --noinput &&
             python manage.py migrate --settings=hopla.settings &&
             /usr/local/bin/gunicorn hopla.wsgi:application  -w 2 -b :8000"
    links:
      - redis:redis
    depends_on:
      - redis

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - docker/postgres/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"


  celery:
    restart: always
    working_dir: /app
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: celery -A hopla worker -l INFO
    env_file:
      - docker/web/env.env
      - docker/postgres/postgres.env
    links:
      - redis:redis
    depends_on:
      - redis

volumes:
  postgres_data:
