# Generated by Django 4.2.11 on 2024-05-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imageupload",
            name="image_url",
        ),
        migrations.AddField(
            model_name="imageupload",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
